### ISSUE TITLE
Scratch.Json.Tests.scriptRoundTripTest で失敗するケースを発見

### ISSUE THREAD

**Issue by wiinuk** [wiinuk/Wiinuk.Scratch#1]
```
テスト名:	Scratch.Json.Tests.scriptRoundTripTest
テストの完全名:	Scratch.Tests.Scratch.Json.Tests.Scratch.Json.Tests.scriptRoundTripTest
テスト ソース:	C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\Scratch.Json.Tests.fs : 行 27
テスト成果:	失敗
テスト継続期間:	0:00:00

テスト名:	Scratch.Json.Tests.scriptRoundTripTest
テスト成果:	失敗
結果  のスタック トレース:	
at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at <StartupCode$FsCheck>.$Runner.get_throwingRunner@363.FsCheck-IRunner-OnFinished(String name, TestResult testResult)
   at FsCheck.Runner.check[a](Config config, a p)
   at FsCheck.Check.One[Testable](Config config, Testable property)
   at Scratch.Json.Tests.qcheck[a](a test) in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\Scratch.Json.Tests.fs:line 18
   at Scratch.Json.Tests.roundTripTest[a,b,c](ISyntax`1 syntax, FSharpFunc`2 mapping) in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\Scratch.Json.Tests.fs:line 21
   at Scratch.Json.Tests.scriptRoundTripTest() in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\Scratch.Json.Tests.fs:line 27
結果  のメッセージ:	
System.Exception : Falsifiable, after 27 tests (2 shrinks) (StdGen (1647239324,296660418)):
Original:
Statements
  (BlockExpression
     ((),
      [ComplexExpression
         ((),"*",[Literal ((),SNumber 0.0); Literal ((),SBool false)])]))
Shrunk:
Statements (BlockExpression ((),[ComplexExpression ((),"*",[])]))
with exception:
System.Exception: Expression (ComplexExpression (None,"*",[])) =? Statements (BlockExpression (None,[ComplexExpression (None,"*",[])]))
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at AssertionOperations.op_EqualsQmark@22-1.Invoke(a arg20) in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\AssertionOperations.fs:line 22
   at AssertionOperations.op_EqualsQmark[a](a l, a r) in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\AssertionOperations.fs:line 22
   at Scratch.Json.Tests.roundTripTest@21.Invoke(c x) in C:\Users\User\source\Repos\NewUnityProject.4\external\fspad\tests\Scratch.Tests\Scratch.Json.Tests.fs:line 23
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)
```

**Comment by wiinuk** [comment]
Script.Statements の中に式が1つだけある Script が Script.Expression として読み取られる問題
Script.Statements の直下に式がある場合は違法とし、テストデータを生成しないように修正済み
https://github.com/wiinuk/Wiinuk.Scratch/blob/11a970a3feac7855db6c60d1aaf92c59818dbc2d/tests/Scratch.Runtime.Tests/Scratch.Runtime.Test.Helpers.fs#L145-L146
